import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";

// type Message = RouterOutputs["message"]["getAllByUser"][number];
const Home: NextPage = () => {
  const messages = api.message.getAllByUser.useQuery();
  console.log(messages.data);
  return (
    <>
      <Head>
        <title>Messages</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-800 to-[#15162c] text-white">
        <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
          {messages?.data?.map((message) => (
            <div key={message.id}>{message.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
